sudo: true
language: cpp
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # valgrind, for memcheck
  - sudo apt-get install -qq valgrind

script: 
  # Build and run the tests
  - qmake the_richel_setup_test.pro
  - make debug
  - ./the_richel_setup_test
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./the_richel_setup_test
  - cat memcheck.log
  # Build and run and profile normal program
  - qmake the_richel_setup.pro
  - make release
  - time ./the_richel_setup
  - gprof the_richel_setup > gprof.log
  - head gprof.log -n 1000
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
